//CARACTERS
export const GET_INFO_CARACTERS = 'GET_INFO_CARACTERS';
export const SET_INFO_CARACTERS = 'SET_INFO_CARACTERS';
export const GET_CARACTERS = 'GET_CARACTERS';
export const SET_CARACTERS = 'SET_CARACTERS';
//CARACTERS
