//CARACTERS
export const GET_INFO_CARACTERS = 'GET_INFO_CARACTERS';
export const SET_INFO_CARACTERS = 'SET_INFO_CARACTERS';
export const GET_CARACTERS = 'GET_CARACTERS';
export const SET_CARACTERS = 'SET_CARACTERS';
export const GET_CARACTERS_CHANGE_PAGE = 'GET_CARACTERS_CHANGE_PAGE';
export const SET_CARACTERS_CHANGE_PAGE = 'SET_CARACTERS_CHANGE_PAGE';
export const SET_CARACTERS_NOT_FOUND = 'SET_CARACTERS_NOT_FOUND';
export const SET_CARACTERS_START_LOADING = 'SET_CARACTERS_START_LOADING';
export const SET_CARACTERS_FINISH_LOADING = 'SET_CARACTERS_FINISH_LOADING';
//CARACTERS
